# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef374d9f6c6f6638306e2d03c1cc60de92dc8453cef12b18293ec38b6ea1481d1f0560b9b5f1e766ca0c93ee885a939dde0cf90e8140bc66ceb1342c4f9041e5

test:
  secret_key_base: 9244b3ad403d5e2fd75baef929c9c8bdcb6b98d0dd1b6b79b8f587f013023a1b8048a4177fb69a464ae0524f096da39ace867706504b8486ec407ff3ab03fc25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
